# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20161030_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='plannedby',
        ),
    ]
